ENV['STORAGE_PATH']       = "uploads" if ENV['STORAGE_PATH'].nil?
#ENV['PRIVATE']           = 'true'
ENV['TITLE']            = 'Ricebowl'
ENV['HEROKU']           = 'false'
#ENV['S3_KEY']           = ''
#ENV['S3_SECRET']        = ''
#ENV['S3_BUCKET']        = ''
#ENV['FACEBOOK_ID']       = ''
#ENV['FACEBOOK_SECRET']   = ''
